### ISSUE TITLE
[nice fonts] \Chop notation broken

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/nominal-lcf-paper#20]
- [x] ~~overline no longer appears; not sure how to fix this? @freebroccolo~~
- [ ] `\setminus` is missing; this one seems like it will be simple to fix

**Comment by jonsterling** [comment]
Ooops, jumped the gun on the overline, that works fine. I'll fix \setminus.

**Comment by freebroccolo** [comment]
Btw, [this link](http://tex.stackexchange.com/a/177023) might be useful.

I also notice that in the `lualatex` output, it says some things like this in a few places:

```
*************************************************
* unicode-math warning: "mathtools-overbracket"
*
* Using \overbracket and \underbracket from `mathtools' package.
*
* Use \Uoverbracket and \Uunderbracket for original `unicode-math' definition.
*************************************************
```

So sometimes you might want to use the `\U` version I guess.
